a=float(input("Enter the first number: "))
b=int(input("Enter the second number: "))
print("We will check if the sum of the numbers is greater than 50.8")
sm=(a+b>50.8)
print(bool(sm))
c=int(input("Enter another number: "))
inter=(c>10 and c<20)
print("We will check if third number is between 10 and 20")
print(bool(inter))
